name = "my-indirect-short"
main = "bin.js"
minify = true
compatibility_date = "2024-11-18"
compatibility_flags = [ "nodejs_als" ]

[build]
command = "node build.mjs"

[[kv_namespaces]]
binding = "MY_KV"
id = "KV_NAMESPACE_ID"

